name: 'Build Nightly'

on:
  pull_request:
    paths: [ "game_client/**" ]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: "us-east-2"
  MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
  MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}

jobs:
  terraform:
    name: "Plan Server"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell
    defaults:
      run:
        working-directory: "data_server/infrastructure"
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Read and load aws credentials
    - name: Load Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::442426877818:role/GithubAction-Deployments
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    # Build using the makefile
    - name: Build Server
      working-directory: "data_server"
      run: make build

    # Install the latest version of Terraform CLI and configure
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory
    - name: Plan Terraform
      run: |
        terraform init
        terraform plan -input=false
