name: 'Build Nightly'

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]
    paths: [ "game_client/**" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-nightly:
    if: github.event.pull_request.merged == true
    name: "Build Nightly Release"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: "game_client"
        shell: bash

    steps:
      - name: Build JAR && Sum
        run: |
          rm -rf lwjgl3/build/libs/*

          ./gradlew lwjgl3:dist

          cd lwjgl3/build/libs; sha256sum *.jar > SHA256Sum.txt

